    file_path <- "E:/Tracy/fall 2024/P8105 Data Science/p8105_hw2_tz2659/"
    options(scipen=999) # Cancel scientific notation when describing dataset

## Problem 1

    library(readr)
    library(dplyr)

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    nyc_subway_data <- read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv")

    ## Rows: 1868 Columns: 32

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Data overview

    n_rows <- nrow(nyc_subway_data)
    n_cols <- ncol(nyc_subway_data)
    head(nyc_subway_data)

    ## # A tibble: 6 × 32
    ##   Division Line     `Station Name` `Station Latitude` `Station Longitude` Route1
    ##   <chr>    <chr>    <chr>                       <dbl>               <dbl> <chr> 
    ## 1 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 2 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 3 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 4 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 5 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 6 BMT      4 Avenue 45th St                      40.6               -74.0 R     
    ## # ℹ 26 more variables: Route2 <chr>, Route3 <chr>, Route4 <chr>, Route5 <chr>,
    ## #   Route6 <chr>, Route7 <chr>, Route8 <dbl>, Route9 <dbl>, Route10 <dbl>,
    ## #   Route11 <dbl>, `Entrance Type` <chr>, Entry <chr>, `Exit Only` <chr>,
    ## #   Vending <chr>, Staffing <chr>, `Staff Hours` <chr>, ADA <lgl>,
    ## #   `ADA Notes` <chr>, `Free Crossover` <lgl>, `North South Street` <chr>,
    ## #   `East West Street` <chr>, Corner <chr>, `Entrance Latitude` <dbl>,
    ## #   `Entrance Longitude` <dbl>, `Station Location` <chr>, …

    n_rows

    ## [1] 1868

    n_cols

    ## [1] 32

### Data cleaning

    # Select columns
    cleaned_data <- nyc_subway_data %>%
      select(Line, `Station Name`, `Station Latitude`, `Station Longitude`, 
             Route1, Route2, Route3, Entry, Vending, `Entrance Type`, ADA)

    # Convert the entry variable from character to a logical variable 
    cleaned_data <- cleaned_data %>%
      mutate(Entry = ifelse(Entry == "YES", TRUE, FALSE))

    head(cleaned_data)

    ## # A tibble: 6 × 11
    ##   Line     `Station Name` `Station Latitude` `Station Longitude` Route1 Route2
    ##   <chr>    <chr>                       <dbl>               <dbl> <chr>  <chr> 
    ## 1 4 Avenue 25th St                      40.7               -74.0 R      <NA>  
    ## 2 4 Avenue 25th St                      40.7               -74.0 R      <NA>  
    ## 3 4 Avenue 36th St                      40.7               -74.0 N      R     
    ## 4 4 Avenue 36th St                      40.7               -74.0 N      R     
    ## 5 4 Avenue 36th St                      40.7               -74.0 N      R     
    ## 6 4 Avenue 45th St                      40.6               -74.0 R      <NA>  
    ## # ℹ 5 more variables: Route3 <chr>, Entry <lgl>, Vending <chr>,
    ## #   `Entrance Type` <chr>, ADA <lgl>

### How many distinct stations are there?

    dist_stations <- cleaned_data %>%
      distinct(`Station Name`, Line) %>%
      nrow()

    dist_stations

    ## [1] 465

### How many stations are ADA compliant?

    ada_stations <- cleaned_data %>%
      filter(ADA == TRUE) %>%
      distinct(`Station Name`, Line) %>%
      nrow()

    ada_stations

    ## [1] 84

### What proportion of station entrances / exits without vending allow entrance?

    no_vend <- cleaned_data %>%
      filter(Vending == "NO") %>%
      nrow() / nrow(cleaned_data)

    no_vend

    ## [1] 0.09796574

### How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?

    # Distinct stations that serve the A train
    atrain_stations <- cleaned_data %>%
      filter(Route1 == "A" | Route2 == "A" | Route3 == "A") %>%
      distinct(`Station Name`, Line) %>%
      nrow()

    # ADA compliant stations serving the A train
    atrain_ada <- cleaned_data %>%
      filter((Route1 == "A" | Route2 == "A" | Route3 == "A") & ADA == TRUE) %>%
      distinct(`Station Name`, Line) %>%
      nrow()

    atrain_stations

    ## [1] 60

    atrain_ada

    ## [1] 17

The dataset contains information on 1868 observations from NYC subway
entrances and exits across different stations. There are 32 variables,
primarily capturing details such as station name and line, station
latitude and longitude, routes, entry permissions and vending machine
availability, ADA compliance, etc.

After data cleaning, this dataset contains 1868 rows and 11 columns.

Results:  
1. There are 465 distinct stations based on station name and line.  
2. Out of the distinct stations, 84 stations are ADA compliant.  
3. Approximately 9.8% of station entrances/exits without vending
machines allow entry.  
4. There are 60 distinct stations that serve the A train. And 17
stations are ADA compliant in these stations.

## Problem 2

*Mr. Trash Wheel*

    library(readxl)
    library(dplyr)
    library(janitor)

    ## 
    ## Attaching package: 'janitor'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

    mr_df <- read_excel("202409 Trash Wheel Collection Data.xlsx", 
                        sheet = "Mr. Trash Wheel", range = "A2:N653") |>
      janitor::clean_names() |>
      mutate(
        trash_wheel = "Mr. Trash Wheel",  
        sports_balls = as.integer(round(sports_balls)), # Round sports balls to integer
        year = as.numeric(year)  
      )

*Professor Trash Wheel*

    pf_df <- read_excel("202409 Trash Wheel Collection Data.xlsx", 
                        sheet = "Professor Trash Wheel", range = "A2:M121") |>
      janitor::clean_names() |>
      mutate(
        trash_wheel = "Professor Trash Wheel" 
      )

*Gwynnda Trash Wheel*

    gw_df <- read_excel("202409 Trash Wheel Collection Data.xlsx", 
                                           sheet = "Gwynnda Trash Wheel", range = "A2:L265") |>
      janitor::clean_names() |>
      mutate(
        trash_wheel = "Gwynnda Trash Wheel" 
      )

*Combine datasets*

    combined_df <- bind_rows(mr_df, pf_df, gw_df)

    head(combined_df)

    ## # A tibble: 6 × 15
    ##   dumpster month  year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## 6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

*Clean the combined dataset again*

     # Filter out rows without dumpster-specific data
    clean_df <- combined_df |>
      filter(!is.na(dumpster))
    head(clean_df)

    ## # A tibble: 6 × 15
    ##   dumpster month  year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ## 6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

### Data description

The total dataset contains information on 1033 observations from three
Trash Wheels: Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda Trash
Wheel. The dataset has key variables such as date of collection
(`date`), total weight of trash collected (`weight_tons`), and number of
plastic bottles (`plastic_bottles`) and cigarette butts
(`cigarette_butts`) collected.

The total weight of trash collected by Professor Trash Wheel is 246.74
tons.

The total number of cigarette butts collected by Gwynnda in June of 2022
is 18120.

## Problem 3

    bakers <- read_csv('bakers.csv', na = c("NA", " ")) |>
      clean_names()|>
      janitor::clean_names() |>
      rename(baker = baker_name)

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    bakes <- read_csv('bakes.csv', na = c("NA", "N/A", " ")) |>
      clean_names()|>
      janitor::clean_names()

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    results <- read_csv('results.csv', skip = 2, na = c("NA", " ")) |>
      clean_names()|>
      janitor::clean_names()

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    viewers <- read_csv('viewers.csv', na = c("NA", " ")) |>
      clean_names()|>
      janitor::clean_names()

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    glimpse(bakers)

    ## Rows: 120
    ## Columns: 5
    ## $ baker            <chr> "Ali Imdad", "Alice Fevronia", "Alvin Magallanes", "A…
    ## $ series           <dbl> 4, 10, 6, 10, 7, 1, 9, 4, 2, 7, 3, 9, 7, 3, 5, 8, 4, …
    ## $ baker_age        <dbl> 25, 28, 37, 24, 25, 30, 30, 31, 31, 23, 63, 33, 31, 2…
    ## $ baker_occupation <chr> "Charity worker", "Geography teacher", "Nurse", "Fash…
    ## $ hometown         <chr> "Saltley, Birmingham", "Essex", "Bracknell, Berkshire…

    glimpse(bakes)

    ## Rows: 548
    ## Columns: 5
    ## $ series         <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
    ## $ episode        <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3…
    ## $ baker          <chr> "Annetha", "David", "Edd", "Jasminder", "Jonathan", "Le…
    ## $ signature_bake <chr> "Light Jamaican Black Cakewith Strawberries and Cream",…
    ## $ show_stopper   <chr> "Red, White & Blue Chocolate Cake with Cigarellos, Fres…

    glimpse(results)

    ## Rows: 1,136
    ## Columns: 5
    ## $ series    <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
    ## $ episode   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
    ## $ baker     <chr> "Annetha", "David", "Edd", "Jasminder", "Jonathan", "Louise"…
    ## $ technical <dbl> 2, 3, 1, NA, 9, NA, 8, NA, 10, NA, 8, 6, 2, 1, 3, 5, 7, 4, N…
    ## $ result    <chr> "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "OUT", "OUT"…

    glimpse(viewers)

    ## Rows: 10
    ## Columns: 11
    ## $ episode   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    ## $ series_1  <dbl> 2.24, 3.00, 3.00, 2.60, 3.03, 2.75, NA, NA, NA, NA
    ## $ series_2  <dbl> 3.10, 3.53, 3.82, 3.60, 3.83, 4.25, 4.42, 5.06, NA, NA
    ## $ series_3  <dbl> 3.85, 4.60, 4.53, 4.71, 4.61, 4.82, 5.10, 5.35, 5.70, 6.74
    ## $ series_4  <dbl> 6.60, 6.65, 7.17, 6.82, 6.95, 7.32, 7.76, 7.41, 7.41, 9.45
    ## $ series_5  <dbl> 8.510, 8.790, 9.280, 10.250, 9.950, 10.130, 10.280, 9.023, 1…
    ## $ series_6  <dbl> 11.62, 11.59, 12.01, 12.36, 12.39, 12.00, 12.35, 11.09, 12.6…
    ## $ series_7  <dbl> 13.58, 13.45, 13.01, 13.29, 13.12, 13.13, 13.45, 13.26, 13.4…
    ## $ series_8  <dbl> 9.46, 9.23, 8.68, 8.55, 8.61, 8.61, 9.01, 8.95, 9.03, 10.04
    ## $ series_9  <dbl> 9.55, 9.31, 8.91, 8.88, 8.67, 8.91, 9.22, 9.69, 9.50, 10.34
    ## $ series_10 <dbl> 9.62, 9.38, 8.94, 8.96, 9.26, 8.70, 8.98, 9.19, 9.34, 10.05

    summary(bakers)

    ##     baker               series       baker_age     baker_occupation  
    ##  Length:120         Min.   : 1.0   Min.   :17.00   Length:120        
    ##  Class :character   1st Qu.: 3.0   1st Qu.:28.75   Class :character  
    ##  Mode  :character   Median : 6.0   Median :34.00   Mode  :character  
    ##                     Mean   : 5.6   Mean   :37.39                     
    ##                     3rd Qu.: 8.0   3rd Qu.:45.00                     
    ##                     Max.   :10.0   Max.   :71.00                     
    ##    hometown        
    ##  Length:120        
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ## 

    summary(bakes)

    ##      series        episode          baker           signature_bake    
    ##  Min.   :1.00   Min.   : 1.000   Length:548         Length:548        
    ##  1st Qu.:3.00   1st Qu.: 2.000   Class :character   Class :character  
    ##  Median :5.00   Median : 4.000   Mode  :character   Mode  :character  
    ##  Mean   :4.81   Mean   : 4.192                                        
    ##  3rd Qu.:7.00   3rd Qu.: 6.000                                        
    ##  Max.   :8.00   Max.   :10.000                                        
    ##  show_stopper      
    ##  Length:548        
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ## 

    summary(results)

    ##      series          episode         baker             technical     
    ##  Min.   : 1.000   Min.   : 1.00   Length:1136        Min.   : 1.000  
    ##  1st Qu.: 4.000   1st Qu.: 3.00   Class :character   1st Qu.: 2.000  
    ##  Median : 6.000   Median : 5.00   Mode  :character   Median : 4.000  
    ##  Mean   : 5.838   Mean   : 5.31                      Mean   : 4.843  
    ##  3rd Qu.: 8.000   3rd Qu.: 8.00                      3rd Qu.: 7.000  
    ##  Max.   :10.000   Max.   :10.00                      Max.   :13.000  
    ##                                                      NA's   :440     
    ##     result         
    ##  Length:1136       
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ##                    
    ## 

    summary(viewers)

    ##     episode         series_1        series_2        series_3    
    ##  Min.   : 1.00   Min.   :2.240   Min.   :3.100   Min.   :3.850  
    ##  1st Qu.: 3.25   1st Qu.:2.638   1st Qu.:3.583   1st Qu.:4.603  
    ##  Median : 5.50   Median :2.875   Median :3.825   Median :4.765  
    ##  Mean   : 5.50   Mean   :2.770   Mean   :3.951   Mean   :5.001  
    ##  3rd Qu.: 7.75   3rd Qu.:3.000   3rd Qu.:4.293   3rd Qu.:5.287  
    ##  Max.   :10.00   Max.   :3.030   Max.   :5.060   Max.   :6.740  
    ##                  NA's   :4       NA's   :2                      
    ##     series_4        series_5         series_6        series_7    
    ##  Min.   :6.600   Min.   : 8.510   Min.   :11.09   Min.   :13.01  
    ##  1st Qu.:6.853   1st Qu.: 9.087   1st Qu.:11.71   1st Qu.:13.16  
    ##  Median :7.245   Median :10.040   Median :12.18   Median :13.37  
    ##  Mean   :7.354   Mean   :10.039   Mean   :12.31   Mean   :13.56  
    ##  3rd Qu.:7.410   3rd Qu.:10.273   3rd Qu.:12.38   3rd Qu.:13.45  
    ##  Max.   :9.450   Max.   :13.510   Max.   :15.05   Max.   :15.90  
    ##                                                                  
    ##     series_8         series_9        series_10     
    ##  Min.   : 8.550   Min.   : 8.670   Min.   : 8.700  
    ##  1st Qu.: 8.627   1st Qu.: 8.910   1st Qu.: 8.965  
    ##  Median : 8.980   Median : 9.265   Median : 9.225  
    ##  Mean   : 9.017   Mean   : 9.298   Mean   : 9.242  
    ##  3rd Qu.: 9.180   3rd Qu.: 9.537   3rd Qu.: 9.370  
    ##  Max.   :10.040   Max.   :10.340   Max.   :10.050  
    ## 

### Use `anti-join` to find who do not have corresponding records

    bakers_missing <- results |>
      anti_join(bakers, by = c("baker", "series"))
    bakers_missing

    ## # A tibble: 1,136 × 5
    ##    series episode baker     technical result
    ##     <dbl>   <dbl> <chr>         <dbl> <chr> 
    ##  1      1       1 Annetha           2 IN    
    ##  2      1       1 David             3 IN    
    ##  3      1       1 Edd               1 IN    
    ##  4      1       1 Jasminder        NA IN    
    ##  5      1       1 Jonathan          9 IN    
    ##  6      1       1 Louise           NA IN    
    ##  7      1       1 Miranda           8 IN    
    ##  8      1       1 Ruth             NA IN    
    ##  9      1       1 Lea              10 OUT   
    ## 10      1       1 Mark             NA OUT   
    ## # ℹ 1,126 more rows

    bakes_missing <- results |>
      anti_join(bakes, by = c("baker", "series"))
    bakes_missing

    ## # A tibble: 258 × 5
    ##    series episode baker  technical result    
    ##     <dbl>   <dbl> <chr>      <dbl> <chr>     
    ##  1      2       1 Joanne        11 IN        
    ##  2      2       2 Joanne        10 IN        
    ##  3      2       3 Joanne         1 IN        
    ##  4      2       4 Joanne         8 IN        
    ##  5      2       5 Joanne         6 IN        
    ##  6      2       6 Joanne         1 STAR BAKER
    ##  7      2       7 Joanne         3 IN        
    ##  8      2       8 Joanne         1 WINNER    
    ##  9      9       1 Antony        12 IN        
    ## 10      9       1 Briony         2 IN        
    ## # ℹ 248 more rows

    results_missing <- results |>
      anti_join(results, by = c("baker", "series"))
    results_missing

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <dbl>, episode <dbl>, baker <chr>, technical <dbl>,
    ## #   result <chr>

### Merge datasets

    # Keep first name to merge
    library(tidyverse)

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

    bakers = mutate(bakers, baker = word(baker, 1))

    # Merge to final dataset
    final_df = full_join(bakers, bakes, by = c("baker", "series")) |>
      full_join(results, by = c("baker", "episode", "series")) |>
      select(series, episode, baker, baker_age, baker_occupation, hometown, signature_bake, show_stopper, technical, result)

    write_csv(final_df, "final_df") # Save the merged dataset

### Analyze dataset

Viewership per season

    library(ggplot2)

    viewers_long <- viewers |>
      pivot_longer(cols = starts_with("series_"), 
                   names_to = "series", 
                   values_to = "viewership") |>
      mutate(series = as.numeric(str_remove(series, "series_"))) 

    ggplot(viewers_long, aes(x = series, y = viewership)) +
      geom_line(color = "lightblue") + 
      geom_point(color = "red") +   
      labs(title = "Viewership trends per season", 
           x = "Seasons", 
           y = "Average viewership") +
      theme_minimal()

    ## Warning: Removed 6 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw2_tz2659_files/figure-markdown_strict/unnamed-chunk-18-1.png)
There is a general increase in viewership from Season 1 to Season 6. The
viewership appears to peak around Seasons 4-6. After Season 6, there is
a decline in viewership. There is a sharpest drop between Seasons 6 and
7, followed by a continued but more mild decline until Season 10.

Technical performance vs result

    cleaned_final_df <- final_df |> drop_na(result)

    # Box plot of technical scores by result ("in" vs "out")
    ggplot(cleaned_final_df, aes(x = result, y = technical, fill = result)) +
      geom_boxplot() +
      labs(title = "Technical Performance by Result (In vs Out)",
           x = "Result",
           y = "Technical Performance (1-13)") +
      theme_minimal() +
      theme(legend.position = "none")  # Remove legend since the result is on the x-axis

    ## Warning: Removed 14 rows containing non-finite outside the scale range
    ## (`stat_boxplot()`).

![](p8105_hw2_tz2659_files/figure-markdown_strict/unnamed-chunk-19-1.png)
Technical Performance 1-13 shows the range of technical performance
scores for each result. A lower score means better performance.

Technical performance is generally better for contestants who stayed in
(IN), won Star Baker, or won the competition (WINNER), as seen by the
lower median scores. Contestants who were eliminated (OUT) performed
worse in technical challenges, as indicated by higher median scores. The
narrow range of scores for the winner shows that technical performance
is a good predictor of success in the competition.

### Create a reader-friendly table showing the star baker or winner of each episode in Seasons 5 through 10. Comment on this table – were there any predictable overall winners? Any surprises?

    # Filter the data for Seasons 5 through 10 and focus on Star Baker and Winner results
    star_baker_table <- final_df |>
      filter(series >= 5 & series <= 10) |> 
      filter(result %in% c("STAR BAKER", "WINNER")) |>
      select(series, episode, baker, result) |>
      arrange(series, episode)

    knitr::kable(star_baker_table, 
                 caption = "Star Baker and Winner for Each Episode in Seasons 5 through 10",
                 col.names = c("Season", "Episode", "Baker", "Result"))

<table>
<caption>Star Baker and Winner for Each Episode in Seasons 5 through
10</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Season</th>
<th style="text-align: right;">Episode</th>
<th style="text-align: left;">Baker</th>
<th style="text-align: left;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Nancy</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Richard</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Luis</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Richard</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Kate</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Chetna</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Richard</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Richard</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Richard</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Nancy</td>
<td style="text-align: left;">WINNER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Marie</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Ian</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Ian</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Ian</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Nadiya</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Mat</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Tamal</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Nadiya</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Nadiya</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Nadiya</td>
<td style="text-align: left;">WINNER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Jane</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Candice</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Tom</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Benjamina</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Candice</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Tom</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Andrew</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Candice</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Andrew</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Candice</td>
<td style="text-align: left;">WINNER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Steven</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Steven</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Julia</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Kate</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Sophie</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Liam</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Steven</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Stacey</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Sophie</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Sophie</td>
<td style="text-align: left;">WINNER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Manon</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Rahul</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Rahul</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Dan</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Kim-Joy</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Briony</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Kim-Joy</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Ruby</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Ruby</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Rahul</td>
<td style="text-align: left;">WINNER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Michelle</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Alice</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Michael</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Steph</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Steph</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Steph</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Henry</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Steph</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Alice</td>
<td style="text-align: left;">STAR BAKER</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">David</td>
<td style="text-align: left;">WINNER</td>
</tr>
</tbody>
</table>

Star Baker and Winner for Each Episode in Seasons 5 through 10

Predictable results:

Seasons 6, 7, and 9 show predictable outcomes, where the bakers who won
multiple Star Baker titles (Nadiya, Candice, Rahul) went on to win the
entire season.

Surprising results:

Season 5: Richard’s 5 Star Baker titles didn’t make him to a final
victory. Season 10: David didn’t have any Star Baker title, but he wins
in the end. Steph’s consistent dominance throughout the season, with 4
titles, made her the likely candidate for the winner, but she didn’t
win.

In general, while strong performances often correlate with final
success, surprises still happen.

### Averages of viewership for series 1 and 5

    av_1 = mean(pull(viewers, series_1), na.rm = TRUE)
    av_5 = mean(pull(viewers, series_5), na.rm = TRUE)
    av_1

    ## [1] 2.77

    av_5

    ## [1] 10.0393

The average viewership for series 1 and 5 are 2.77 and 10.0393
